package org.stardust.math.ec;

import java.math.BigInteger;

/**
 * Elliptic curve parameters.
 */
public class ECParameters<T> {

    private final BigInteger p;

    private final BigInteger a;

    private final BigInteger b;

    private final T g;

    private final BigInteger n;

    /**
     * Creates a new set of parameters.
     *
     * @param p The prime number p that indicates the order of the field Fp.
     * @param a The value a used in the curve equation.
     * @param b The value b used in the curve equation.
     * @param g The generator g of the subgroup.
     * @param n The order n of the subgroup generated by g.
     */
    public ECParameters(BigInteger p, BigInteger a, BigInteger b, T g, BigInteger n) {
        this.p = p;
        this.a = a;
        this.b = b;
        this.g = g;
        this.n = n;
    }

    /**
     * The prime number p that indicates the order of the field Fp.
     */
    public BigInteger getP() {
        return p;
    }

    /**
     * The value a used in the curve equation.
     */
    public BigInteger getA() {
        return a;
    }

    /**
     * The value b used in the curve equation.
     */
    public BigInteger getB() {
        return b;
    }

    /**
     * The generator g of the subgroup.
     */
    public T getG() {
        return g;
    }

    /**
     * The order n of the subgroup generated by g.
     */
    public BigInteger getN() {
        return n;
    }
}
