package org.stardust.math;

/**
 * Created with IntelliJ IDEA.
 * User: evadrone
 * Date: 8/18/13
 * Time: 5:33 PM
 * To change this template use File | Settings | File Templates.
 */
public class EllipticCurveParameters {
    /**
     * The prime number p that indicates the order of the field Fp.
     */
    private int p;

    /**
     * The value a used in the curve equation.
     */
    private int a;

    /**
     * The value b used in the curve equation.
     */
    private int b;

    /**
     * The generator g of the subgroup.
     */
    private int g;

    /**
     * The order n of the subgroup generated by g.
     */
    private int n;

    /**
     * Creates a new set of parameters.
     *
     * @param p The prime number p that indicates the order of the field Fp.
     * @param a The value a used in the curve equation.
     * @param b The value b used in the curve equation.
     * @param g The generator g of the subgroup.
     * @param n The order n of the subgroup generated by g.
     */
    public EllipticCurveParameters(int p, int a, int b, int g, int n) {
        this.p = p;
        this.a = a;
        this.b = b;
        this.g = g;
        this.n = n;
    }
}
