package org.stardust.math;

import java.math.BigInteger;

/**
 * A finite group.
 */
public interface FiniteGroup<T> extends Group<T> {

    /**
     * Returns the number of elements in the group.
     *
     * @return the number of elements in the group.
     */
    public BigInteger getGroupOrder();

    /**
     * Returns the smallest positive integer x such that xa = e
     *
     * @param a A group element
     * @return the smallest positive integer x such that xa = e
     */
    public BigInteger getOrder(T a);

    /**
     * Returns the cyclic subgroup generated by <code>a</code>
     *
     * @param a The generator
     * @return the cyclic subgroup generated by <code>a</code>
     */
    public FiniteGroup<T> getCyclicSubgroup(T a);
}
